In [1]:
from network import CNetwork

In [2]:
import pandas as pd
import numpy as np

In [3]:
from utils import verifyDir

In [4]:
name_dataset = "dataset_2"
length_cut = 1000
random_flag = True

In [5]:
auxiliar_path = 'auxiliar_folder/' + name_dataset   + '/'
verifyDir(auxiliar_path)

In [6]:
df_train = pd.read_csv("df_train_" + name_dataset + "_" + str(length_cut) + "_" + str(random_flag) + ".csv")

In [7]:
df_val = pd.read_csv("df_val_" + name_dataset + "_" + str(length_cut) + "_" + str(random_flag) + ".csv")

In [8]:
df_test = pd.read_csv("df_test_" + name_dataset + "_" + str(length_cut) + "_" + str(random_flag) + ".csv")

In [9]:
df_train.head(5)

Unnamed: 0                                               text  \
0           0  I saw through the open door way a lonely girl ...   
1           1  It is my father s fatal science No no Giovanni...   
2           2  left on the earth to show that it was all some...   
3           3  blowing through the cracks of the floor It was...   
4           4  alive from fathoms Mr Couthouy Remarks on Cora...   

                label  
0      hermanMelville  
1  nathanielHawthorne  
2             bmBower  
3          andrewLang  
4       charlesDarwin

In [10]:
from utils.text_processing import get_word_index, get_sequences, get_common_words, pre_process_text

In [11]:
df_train['text'] = df_train['text'].apply(lambda t: pre_process_text(t, remove_stop_words=False, only_stop_words=True))

In [12]:
df_test['text'] = df_test['text'].apply(lambda t: pre_process_text(t, remove_stop_words=False, only_stop_words=True))

In [13]:
df_val['text'] = df_val['text'].apply(lambda t: pre_process_text(t, remove_stop_words=False, only_stop_words=True))

In [14]:
from manager2 import graph2vec

In [15]:
!pip install networkx

In [16]:
def get_graph2vec_features(sequences):
    measures = ["dgr_n", "btw", "cc", "sp", "sp_std", "accs_h2", "accs_h3"]
    network_features = pd.DataFrame()
    nets = []
    for text in sequences:
        obj = CNetwork(text, model=None, index_word=None, percentages=None, path=auxiliar_path)
        network = obj.create_network()
        nets.append(network)
    network_features = np.array(graph2vec("", "linux", nets))
    print(network_features.shape)
        #local_measure = obj.get_network_measures(network, word_features)
        #a_series = pd.Series(local_measure)
        #network_features = network_features.append(a_series, ignore_index=True)
        #network_features = np.vstack([network_features, global_measure]) if len(network_features) > 0 else global_measure
    return network_features

In [17]:
word_index, index_word = get_word_index(df_train["text"])
sequences = get_sequences(df_train["text"], word_index)

In [18]:
X_train = get_graph2vec_features(sequences)

Nodes: 123 - Edges: 418
Nodes: 104 - Edges: 347
Nodes: 86 - Edges: 281
Nodes: 102 - Edges: 344
Nodes: 81 - Edges: 262
Nodes: 111 - Edges: 351
Nodes: 103 - Edges: 386
Nodes: 94 - Edges: 328
Nodes: 107 - Edges: 407
Nodes: 86 - Edges: 280
Nodes: 120 - Edges: 412
Nodes: 108 - Edges: 377
Nodes: 107 - Edges: 386
Nodes: 86 - Edges: 331
Nodes: 99 - Edges: 342
Nodes: 105 - Edges: 369
Nodes: 114 - Edges: 411
Nodes: 113 - Edges: 376
Nodes: 103 - Edges: 347
Nodes: 110 - Edges: 395
Nodes: 101 - Edges: 363
Nodes: 113 - Edges: 408
Nodes: 117 - Edges: 408
Nodes: 112 - Edges: 385
Nodes: 95 - Edges: 292
Nodes: 95 - Edges: 310
Nodes: 110 - Edges: 361
Nodes: 99 - Edges: 323
Nodes: 88 - Edges: 297
Nodes: 100 - Edges: 364
Nodes: 107 - Edges: 371
Nodes: 127 - Edges: 470
Nodes: 102 - Edges: 395
Nodes: 96 - Edges: 342
Nodes: 100 - Edges: 331
Nodes: 104 - Edges: 342
Nodes: 102 - Edges: 309
Nodes: 95 - Edges: 339
Nodes: 90 - Edges: 278
Nodes: 115 - Edges: 417
Nodes: 93 - Edges: 330
Nodes: 114 - Edges: 339
Nodes:

  0%|          | 0/60 [00:00<?, ?it/s]


Feature extraction started.



100%|██████████| 60/60 [00:00<00:00, 110.20it/s]


Optimization started.



graph2vec
(60, 513)


In [19]:
X_train.shape

(60, 513)

In [20]:
X_val = get_graph2vec_features(get_sequences(df_val["text"], word_index))

Nodes: 96 - Edges: 364
Nodes: 88 - Edges: 317
Nodes: 107 - Edges: 373
Nodes: 119 - Edges: 386
Nodes: 109 - Edges: 358
Nodes: 110 - Edges: 393
Nodes: 104 - Edges: 394
Nodes: 100 - Edges: 287
Nodes: 100 - Edges: 336
Nodes: 107 - Edges: 361
Nodes: 91 - Edges: 311
Nodes: 110 - Edges: 377
Nodes: 94 - Edges: 313
Nodes: 108 - Edges: 397
Nodes: 97 - Edges: 329
Nodes: 89 - Edges: 291
Nodes: 103 - Edges: 352
Nodes: 119 - Edges: 390
Nodes: 101 - Edges: 404
Nodes: 120 - Edges: 397
Existe


  0%|          | 0/60 [00:00<?, ?it/s]


Feature extraction started.



100%|██████████| 60/60 [00:00<00:00, 96.80it/s]



Optimization started.

graph2vec
(20, 513)


In [21]:
X_val.shape

(20, 513)

In [22]:
classes = list(df_train['label'])  ## or 'author'
total_classes = list(set(df_train['label']))  ## or author
print("Classes: {}".format(total_classes))
print("Total classes: {}".format(len(total_classes)))
number_books = (df_train[df_train['label'] == total_classes[0]]).shape[0]
print("Total entities for each class in train: {}".format(number_books))
dict_categories = list(set(classes))
dict_categories = {cat: index for index, cat in enumerate(dict_categories)}

Classes: ['whashingtonIrving', 'andrewLang', 'hgWells', 'henryJames', 'allanPoe', 'charlesDarwin', 'markTwain', 'hectorMunro', 'nathanielHawthorne', 'zaneGrey', 'arthurDoyle', 'horatioAlger', 'richardHarding', 'thomasHardy', 'janeAusten', 'charlesDickens', 'hermanMelville', 'pgWodehouse', 'bmBower', 'bramStoker']
Total classes: 20
Total entities for each class in train: 3


In [23]:
y_train = [dict_categories[y] for y in df_train["label"]]

In [24]:
y_val = [dict_categories[y] for y in df_val["label"]]

In [31]:
X_train

array([[ 0.00000000e+00,  1.59596708e-02,  3.44870123e-03, ...,
         9.90505051e-03,  3.99466557e-03, -3.47805396e-03],
       [ 1.00000000e+00,  2.11192202e-02,  3.70291295e-03, ...,
         1.30059281e-02,  4.45512636e-03, -5.13168564e-03],
       [ 2.00000000e+00,  1.38613554e-02,  3.12729017e-03, ...,
         7.50998734e-03,  2.59151892e-03, -2.30660802e-03],
       ...,
       [ 5.70000000e+01,  2.10642610e-02,  4.76927683e-03, ...,
         1.33396070e-02,  5.44338208e-03, -5.34721278e-03],
       [ 5.80000000e+01,  1.29139982e-02,  2.05798191e-03, ...,
         7.33312825e-03,  4.12028795e-03, -2.72408593e-03],
       [ 5.90000000e+01,  1.22972187e-02,  2.56084744e-03, ...,
         8.34067352e-03,  3.59506370e-03, -2.86866492e-03]])

In [32]:
y_train

[16,
 8,
 18,
 1,
 5,
 13,
 13,
 6,
 14,
 0,
 17,
 13,
 1,
 3,
 19,
 18,
 11,
 16,
 6,
 11,
 1,
 9,
 12,
 12,
 12,
 2,
 19,
 4,
 0,
 19,
 8,
 3,
 14,
 15,
 10,
 15,
 7,
 17,
 0,
 17,
 7,
 18,
 11,
 14,
 4,
 6,
 5,
 16,
 9,
 7,
 3,
 5,
 10,
 4,
 8,
 10,
 2,
 9,
 2,
 15]

# Training with Bayes

In [33]:
from classifierv2 import getClassifier, getClassMetrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, y_train)

predicted = knn_clf.predict(X_val)
print(X_train)
print(y_train)
print(y_val)
print(predicted)
#print accuracy_score
print("accuracy : " + str(accuracy_score(y_val, predicted)))

print("micro f-measure " + str(f1_score(y_val, predicted, average='micro')))

[[ 0.00000000e+00  1.59596708e-02  3.44870123e-03 ...  9.90505051e-03
   3.99466557e-03 -3.47805396e-03]
 [ 1.00000000e+00  2.11192202e-02  3.70291295e-03 ...  1.30059281e-02
   4.45512636e-03 -5.13168564e-03]
 [ 2.00000000e+00  1.38613554e-02  3.12729017e-03 ...  7.50998734e-03
   2.59151892e-03 -2.30660802e-03]
 ...
 [ 5.70000000e+01  2.10642610e-02  4.76927683e-03 ...  1.33396070e-02
   5.44338208e-03 -5.34721278e-03]
 [ 5.80000000e+01  1.29139982e-02  2.05798191e-03 ...  7.33312825e-03
   4.12028795e-03 -2.72408593e-03]
 [ 5.90000000e+01  1.22972187e-02  2.56084744e-03 ...  8.34067352e-03
   3.59506370e-03 -2.86866492e-03]]
[16, 8, 18, 1, 5, 13, 13, 6, 14, 0, 17, 13, 1, 3, 19, 18, 11, 16, 6, 11, 1, 9, 12, 12, 12, 2, 19, 4, 0, 19, 8, 3, 14, 15, 10, 15, 7, 17, 0, 17, 7, 18, 11, 14, 4, 6, 5, 16, 9, 7, 3, 5, 10, 4, 8, 10, 2, 9, 2, 15]
[5, 0, 11, 15, 18, 4, 14, 12, 7, 3, 6, 10, 16, 1, 13, 2, 8, 9, 19, 17]
[ 1  1  1  1 13 13 13 13  0  0  0  0  1  1  1  3  6 11 11  1]
accuracy : 0.05
micr

In [36]:
from sklearn.svm import SVC

In [37]:
svc = SVC(kernel='linear', probability=True)
svc.fit(X_train, y_train)

predicted = svc.predict(X_val)
print(X_train)
print(y_train)
print(y_val)
print(predicted)
#print accuracy_score
print("accuracy : " + str(accuracy_score(y_val, predicted)))

print("micro f-measure " + str(f1_score(y_val, predicted, average='micro')))

[[ 0.00000000e+00  1.59596708e-02  3.44870123e-03 ...  9.90505051e-03
   3.99466557e-03 -3.47805396e-03]
 [ 1.00000000e+00  2.11192202e-02  3.70291295e-03 ...  1.30059281e-02
   4.45512636e-03 -5.13168564e-03]
 [ 2.00000000e+00  1.38613554e-02  3.12729017e-03 ...  7.50998734e-03
   2.59151892e-03 -2.30660802e-03]
 ...
 [ 5.70000000e+01  2.10642610e-02  4.76927683e-03 ...  1.33396070e-02
   5.44338208e-03 -5.34721278e-03]
 [ 5.80000000e+01  1.29139982e-02  2.05798191e-03 ...  7.33312825e-03
   4.12028795e-03 -2.72408593e-03]
 [ 5.90000000e+01  1.22972187e-02  2.56084744e-03 ...  8.34067352e-03
   3.59506370e-03 -2.86866492e-03]]
[16, 8, 18, 1, 5, 13, 13, 6, 14, 0, 17, 13, 1, 3, 19, 18, 11, 16, 6, 11, 1, 9, 12, 12, 12, 2, 19, 4, 0, 19, 8, 3, 14, 15, 10, 15, 7, 17, 0, 17, 7, 18, 11, 14, 4, 6, 5, 16, 9, 7, 3, 5, 10, 4, 8, 10, 2, 9, 2, 15]
[5, 0, 11, 15, 18, 4, 14, 12, 7, 3, 6, 10, 16, 1, 13, 2, 8, 9, 19, 17]
[13 13 13 13 13 13 13 13 13 13 13 13  1  1  1  1  1  1  1  1]
accuracy : 0.05
micr